### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by mastergreen15** [miguelssimao/patreon-sort#1]
Ok I've spent hours trying to understand how to run this script. Frankly I have no idea what i'm doing. Could you possibly add a guide or something. I think i have the right modules installed but I have no clue how to run it.

**Comment by miguelssimao** [comment]
Hey there @mastergreen15, sorry about it. I will eventually write detailed instructions for this repository.

For now, please edit the ``settings.py`` file inside the ``lib`` directory and replace ``profileUsername`` with the Patreon username you'd like to sort. By default, the script will only select public tier posts with images so, if you'd like to change this behavior, then set the variables ``postsImagesOnly`` and ``postsPublicOnly`` to False, depending on what you're looking for. 

After that, you can run one of the main files directly from the console. Run the ``sort_by_likes.py`` file to sort your posts by likes in descending order or run the ``sort_by_comments.py`` file to sort them by comments instead.
